type ProductData = {
  brand: string;
  collection_name: string[];
  description: string;
  handle: string;
  id: string;
  imageUrl: string;
  intellisuggestData: string;
  intellisuggestSignaturae: string;
  mfield_filter_colour: string[];
  mfield_filter_globe_base: string[];
  mfield_filter_height: string[];
  mfield_filter_ip_rating: string[];
  mfield_filter_material: string[];
  mfield_filter_style: string[];
  mfield_filter_wattage: string[];
  msrp: string;
  name: string;
  popularity: string;
  price: string;
  product_type_unigram: string;
  rating: string;
  ratingCount: string;
  sku: string;
  ss_available: string;
  ss_has_image: string;
  ss_id: string;
  ss_instock_pct: string;
  ss_is_published: string;
  ss_on_sale: string;
  ss_pct_off: string;
  ss_sku: string;
  tags: string[];
  thumbnailImageUrl: string;
  uid: string;
  url: string;
  variant_sku: string[];
};

type SortData = {
  field: string;
  direction: string;
  label: string;
};
